version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"

  mailcatcher:
    image: zolweb/docker-mailcatcher
    ports:
      - "1080:1080"

  rails:
    depends_on:
      - mysql
      - mailcatcher
    build: .
    command:
      [ "bash", "-c", "rm -f tmp/pids/server.pid; bundle exec puma -C config/puma.rb" ]
    mem_limit: 384m
    environment:
      DISABLE_SPRING: "1"
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
    links:
      - "mysql"
