version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"

  rails:
    depends_on:
      - mysql
    build: .
    command:
      [ "bash", "-c", "rm -f tmp/pids/server.pid; ./bin/rails server -b 0.0.0.0" ]
    mem_limit: 384m
    environment:
      DISABLE_SPRING: "1"
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
    links:
      - "mysql"
